---
- hosts: control
  become: true
  tasks:
    - name: install tools
      apt: 
        name: "{{ paczki }}"
        state: present
        update_cache: yes
      vars:
        paczki:
            - curl
            - cmatrix

