---
# Bring stack down
- hosts: loadbalancer
  connection: paramiko
  become: true
  tasks:
    - service: name=nginx state=stopped

- hosts: webserver
  connection: paramiko
  become: true
  tasks:
    - service: name=apache2 state=stopped

# Restart mysql
- hosts: database
  connection: paramiko
  become: true
  tasks:
    - service: name=mysql state=restarted

# Bring stack up
- hosts: webserver
  connection: paramiko
  become: true
  tasks:
    - service: name=apache2 state=started

- hosts: loadbalancer
  connection: paramiko
  become: true
  tasks:
    - service: name=nginx state=started
