---
 - name: "testowanko!"
   hosts: app01
   connection: paramiko
   tasks:
       - command: hostname

 - name: "wyjscie na swiat"
   hosts: db01
   connection: paramiko
   tasks:
       - command: curl google.com

 - name: "spinguj"
   hosts: lb01
   connection: paramiko
   tasks:
       - command: ping control
